# -*- coding: utf-8 -*-
"""SemEval-2026-Task4 - data2drs

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xAbmwPSK9JCZsJMUHl2yiQrWy84uz3P8
"""


# just to be safe, install java for py_heideltime
#!apt-get update
#!apt-get install -y default-jre default-jdk

#!java -version

#!pip install text2story==1.6.9.3

#!pip show text2story

#!pip install unidecode

import json
import text2story as t2s
import os

from unidecode import unidecode

data_dir = "data/synthetic/"
data_file = os.path.join(data_dir,"synthetic_data_for_classification.jsonl")
data_dir_drs = os.path.join(data_dir,"drs")
data_dir_brat = os.path.join(data_dir,"brat")

t2s.load("en")

"""# Narrative to BRAT"""

def narrative2brat(text):
    doc = t2s.Narrative('en', text, '2020-05-30')
    doc.extract_participants()
    doc.extract_events()
    doc.extract_times()
    doc.extract_semantic_role_links()
    doc.extract_objectal_links()
    return doc.ISO_annotation()

with open(data_file, "r") as fd:
    for idx,line in enumerate(fd):

        data = json.loads(line)

        print(f"Processing anchor number {idx}")
        anchor_brat_txt = narrative2brat(unidecode(data["anchor_text"]))
        anchor_brat_file = os.path.join(data_dir_brat, f"{idx}_anchor.ann")
        with open(anchor_brat_file, "w") as f:
            f.write(anchor_brat_txt)


        print(f"Processing narrative **a** number {idx}")
        doca_brat_txt = narrative2brat(unidecode(data["text_a"]))
        doca_brat_file = os.path.join(data_dir_brat, f"{idx}_a.ann")
        with open(doca_brat_file, "w") as f:
            f.write(doca_brat_txt)


        print(f"Processing narrative **b** number {idx}")
        docb_brat_txt = narrative2brat(unidecode(data["text_b"]))
        docb_brat_file = os.path.join(data_dir_brat, f"{idx}_b.ann")
        with open(docb_brat_file, "w") as f:
            f.write(docb_brat_txt)


