"""
DRS Parser - Extract features from DRS output files

Parses DRS files generated by brat2drs.py and extracts:
- Events with attributes (Type, Tense, Aspect, Vform, Pos)
- Temporal relations (occursBefore, overlaps, during, etc.)
- Semantic relations (agent, patient, etc.)
- Participants (actors)
"""

import re
from collections import defaultdict, Counter


class DRSParser:
    """Parser for DRS output files."""

    def __init__(self, filepath):
        self.filepath = filepath
        self.events = []
        self.actors = {}
        self.relations = []
        self.temporal_relations = []
        self.semantic_relations = []

    def parse(self):
        """Main parsing function."""
        with open(self.filepath, 'r', encoding='utf-8') as f:
            content = f.read()

        # Split into sections
        sections = self._split_sections(content)

        # Parse each section
        if 'EVENTS' in sections:
            self.events = self._parse_events(sections['EVENTS'])

        if 'ACTORS' in sections:
            self.actors = self._parse_actors(sections['ACTORS'])

        if 'RELATIONS' in sections:
            self.relations = self._parse_relations(sections['RELATIONS'])
            self._categorize_relations()

        return self

    def _split_sections(self, content):
        """Split DRS content into sections (EVENTS, ACTORS, RELATIONS)."""
        sections = {}
        current_section = None
        current_content = []

        for line in content.split('\n'):
            if line.startswith('» '):
                # Save previous section
                if current_section:
                    sections[current_section] = '\n'.join(current_content)

                # Start new section
                current_section = line.replace('» ', '').strip()
                current_content = []
            else:
                current_content.append(line)

        # Save last section
        if current_section:
            sections[current_section] = '\n'.join(current_content)

        return sections

    def _parse_events(self, events_section):
        """
        Parse EVENTS section.

        Example:
        # T40 (follows) -> a
        # FOL:  exists Present Verb a.(event(a) & Pos(a,Verb) & Tense(a,Present))
        # DRS:  ([a],[event(a), Pos(a,Verb), Tense(a,Present)])
        """
        events = []
        lines = events_section.split('\n')

        i = 0
        while i < len(lines):
            line = lines[i].strip()

            # Look for event header: # T40 (follows) -> a
            if line.startswith('#') and '->' in line:
                event = self._parse_event_entry(line, lines[i:i + 3])
                if event:
                    events.append(event)
                i += 3  # Skip FOL and DRS lines
            else:
                i += 1

        return events

    def _parse_event_entry(self, header_line, context_lines):
        """
        Parse a single event entry.

        Args:
            header_line: # T40 (follows) -> a
            context_lines: Following lines with FOL and DRS
        """
        # Parse header: # T40 (follows) -> a
        header_match = re.match(r'#\s+(T\d+)\s+\((.+?)\)\s+->\s+(\w+)', header_line)
        if not header_match:
            return None

        event_id, event_text, variable = header_match.groups()

        # Extract attributes from FOL line
        attributes = {}
        for line in context_lines:
            if 'FOL:' in line or 'DRS:' in line:
                # Extract attributes like Type(a,State), Tense(a,Past), etc.
                attributes.update(self._extract_attributes(line))

        return {
            'id': event_id,
            'text': event_text,
            'variable': variable,
            'type': attributes.get('Type'),
            'tense': attributes.get('Tense'),
            'aspect': attributes.get('Aspect'),
            'vform': attributes.get('Vform'),
            'pos': attributes.get('Pos'),
            'attributes': attributes
        }

    def _extract_attributes(self, line):
        """
        Extract attributes from FOL/DRS line.

        Examples:
        - Type(a,State) → {'Type': 'State'}
        - Tense(a,Past) → {'Tense': 'Past'}
        - occursBefore(a,b) → temporal relation (handled separately)
        """
        attributes = {}

        # Pattern for attribute(variable, value)
        attr_pattern = r'(\w+)\([a-z]+,\s*([^)]+)\)'
        matches = re.findall(attr_pattern, line)

        for attr_name, attr_value in matches:
            # Skip relation-like attributes
            if attr_name in ['relationRole', 'occursBefore', 'occursAfter',
                             'overlaps', 'during', 'resultState', 'at_time']:
                continue

            attributes[attr_name] = attr_value.strip()

        return attributes

    def _parse_actors(self, actors_section):
        """
        Parse ACTORS section.

        Example:
        # T1 -> The book
        # T2 -> an international organization
        """
        actors = {}

        for line in actors_section.split('\n'):
            line = line.strip()
            if line.startswith('#'):
                # Parse: # T1 -> The book
                match = re.match(r'#\s+(T\d+)\s+->\s+(.+)', line)
                if match:
                    actor_id, actor_text = match.groups()
                    actors[actor_id] = actor_text.strip()

        return actors

    def _parse_relations(self, relations_section):
        """
        Parse RELATIONS section.

        Example:
        # T1 - agent - T40
        # T7 - objIdentity - T8
        """
        relations = []

        for line in relations_section.split('\n'):
            line = line.strip()
            if line.startswith('#'):
                # Parse: # T1 - agent - T40
                match = re.match(r'#\s+(T\d+)\s+-\s+(\w+)\s+-\s+(T\d+)', line)
                if match:
                    source, rel_type, target = match.groups()
                    relations.append({
                        'source': source,
                        'type': rel_type,
                        'target': target
                    })

        return relations

    def _categorize_relations(self):
        """Separate relations into temporal and semantic."""
        temporal_types = {
            'occursBefore', 'occursAfter', 'overlaps', 'during',
            'resultState', 'at_time', 'completedBefore', 'TLINK'
        }

        for rel in self.relations:
            if any(t in rel['type'] for t in temporal_types):
                self.temporal_relations.append(rel)
            else:
                self.semantic_relations.append(rel)

    # ========== Feature Extraction Methods ==========

    def get_event_count(self):
        """Total number of events."""
        return len(self.events)

    def get_event_type_distribution(self):
        """
        Distribution of event types.

        Returns:
            dict: {'State': 10, 'Process': 5, 'Transition': 8, None: 2}
        """
        return Counter(e['type'] for e in self.events)

    def get_tense_distribution(self):
        """Distribution of tenses."""
        return Counter(e['tense'] for e in self.events)

    def get_aspect_distribution(self):
        """Distribution of aspects."""
        return Counter(e['aspect'] for e in self.events)

    def get_temporal_relation_types(self):
        """
        Count of each temporal relation type.

        Returns:
            dict: {'occursBefore': 5, 'overlaps': 2, etc.}
        """
        return Counter(r['type'] for r in self.temporal_relations)

    def get_semantic_relation_types(self):
        """Count of each semantic relation type."""
        return Counter(r['type'] for r in self.semantic_relations)

    def get_actor_count(self):
        """Number of actors/participants."""
        return len(self.actors)

    def get_relation_count(self):
        """Total number of relations."""
        return len(self.relations)

    def get_temporal_density(self):
        """
        Temporal relation density: ratio of temporal relations to events.

        Higher density = more temporally structured narrative.
        """
        if self.get_event_count() == 0:
            return 0.0
        return len(self.temporal_relations) / self.get_event_count()

    def get_feature_vector(self):
        """
        Extract complete feature vector from DRS.

        Returns:
            dict: All extracted features
        """
        event_types = self.get_event_type_distribution()
        tenses = self.get_tense_distribution()
        aspects = self.get_aspect_distribution()
        temp_rels = self.get_temporal_relation_types()
        sem_rels = self.get_semantic_relation_types()

        return {
            # Basic counts
            'event_count': self.get_event_count(),
            'actor_count': self.get_actor_count(),
            'relation_count': self.get_relation_count(),
            'temporal_relation_count': len(self.temporal_relations),
            'semantic_relation_count': len(self.semantic_relations),

            # Event type distribution
            'state_count': event_types.get('State', 0),
            'process_count': event_types.get('Process', 0),
            'transition_count': event_types.get('Transition', 0),
            'state_ratio': event_types.get('State', 0) / max(self.get_event_count(), 1),
            'process_ratio': event_types.get('Process', 0) / max(self.get_event_count(), 1),
            'transition_ratio': event_types.get('Transition', 0) / max(self.get_event_count(), 1),

            # Tense distribution
            'past_count': tenses.get('Past', 0),
            'present_count': tenses.get('Present', 0),
            'future_count': tenses.get('Future', 0),

            # Aspect distribution
            'perfective_count': aspects.get('Perfective', 0),
            'progressive_count': aspects.get('Progressive', 0),

            # Temporal relations
            'occurs_before_count': temp_rels.get('occursBefore', 0),
            'occurs_after_count': temp_rels.get('occursAfter', 0),
            'overlaps_count': temp_rels.get('overlaps', 0),
            'during_count': temp_rels.get('during', 0),
            'result_state_count': temp_rels.get('resultState', 0),

            # Density metrics
            'temporal_density': self.get_temporal_density(),
            'relation_density': self.get_relation_count() / max(self.get_event_count(), 1),

            # Semantic relations
            'agent_count': sem_rels.get('agent', 0),
            'patient_count': sem_rels.get('patient', 0),
            'coreference_count': sem_rels.get('objIdentity', 0),
        }

    def __repr__(self):
        return (f"DRSParser({self.get_event_count()} events, "
                f"{self.get_actor_count()} actors, "
                f"{self.get_relation_count()} relations)")


# ========== Convenience Functions ==========

def parse_drs_file(filepath):
    """
    Parse a DRS file and return parser object.

    Usage:
        parser = parse_drs_file('0_anchor_drs.txt')
        features = parser.get_feature_vector()
    """
    parser = DRSParser(filepath)
    parser.parse()
    return parser


def extract_features(filepath):
    """
    Quick function to extract features from a DRS file.

    Usage:
        features = extract_features('0_anchor_drs.txt')
    """
    parser = parse_drs_file(filepath)
    return parser.get_feature_vector()


# ========== Testing ==========

if __name__ == "__main__":
    import sys

    if len(sys.argv) < 2:
        print("Usage: python drs_parser.py <drs_file>")
        print("\nExample:")
        print("  python drs_parser.py 0_anchor_drs.txt")
        sys.exit(1)

    filepath = sys.argv[1]

    print(f"Parsing: {filepath}")
    print("=" * 60)

    parser = parse_drs_file(filepath)

    print(f"\n{parser}")
    print("\nEvent Type Distribution:", dict(parser.get_event_type_distribution()))
    print("Tense Distribution:", dict(parser.get_tense_distribution()))
    print("Temporal Relations:", dict(parser.get_temporal_relation_types()))
    print(f"\nTemporal Density: {parser.get_temporal_density():.3f}")

    print("\n" + "=" * 60)
    print("FEATURE VECTOR:")
    print("=" * 60)
    features = parser.get_feature_vector()
    for key, value in sorted(features.items()):
        print(f"  {key:30s}: {value}")