"""
DRS Parser - Extract features from DRS output files

Parses DRS files generated by brat2drs.py and extracts:
- Events with attributes (Type, Tense, Aspect, Vform, Pos)
- Temporal relations (occursBefore, overlaps, during, etc.)
- Semantic relations (agent, patient, etc.)
- Participants (actors)
"""

import re
from collections import defaultdict, Counter
import networkx as nx
from nltk.corpus import verbnet

import spacy


_SPACY_MODEL = None


def _get_spacy_model():
    """Get cached BERT model (load once, reuse)."""
    global _SPACY_MODEL
    if _SPACY_MODEL is None:
        print("Loading spacy model (one-time, ~3 seconds)...")
        _SPACY_MODEL = spacy.load('en_core_web_lg')
        print("✓ spacy model loaded!")
    return _SPACY_MODEL

class DRSParser:
    """Parser for DRS output files."""
    _verbnet_normalizer = None

    def __init__(self, filepath):
        self.filepath = filepath
        self.events = []
        self.actors = {}
        self.relations = []
        self.temporal_relations = []
        self.semantic_relations = []

        if DRSParser._verbnet_normalizer is None:
            DRSParser._init_verbnet_class()

        self.event_normalizer = DRSParser._verbnet_normalizer

    @classmethod
    def _init_verbnet_class(cls):
        """Initialize VerbNet normalizer once for all instances."""
        try:
            from nltk.corpus import verbnet as vn

            cls._verbnet_normalizer = {}

            for classid in vn.classids():
                vnclass = vn.vnclass(classid)
                parent_class = '-'.join(classid.split('-')[:2])

                for member in vnclass.findall('MEMBERS/MEMBER'):
                    verb = member.get('name')
                    if verb:
                        cls._verbnet_normalizer[verb] = parent_class

            print(f"✓ VerbNet loaded: {len(cls._verbnet_normalizer)} verbs")
        except Exception as e:
            print(f"Warning: VerbNet not available: {e}")
            cls._verbnet_normalizer = {}

    def _normalize_event(self, event_text):
        """Normalize event using VerbNet."""

        # Parse text to extract verb
        nlp = _get_spacy_model()
        doc = nlp(event_text.lower())

        # Find main verb (first VERB POS tag)
        verb = None
        for token in doc:
            if token.pos_ == 'VERB':
                verb = token.lemma_
                break

        if not verb:
            return event_text.lower()  # Fallback to original

        # Map to VerbNet class
        return self.event_normalizer.get(verb, verb)

    def parse(self):
        """Main parsing function."""
        with open(self.filepath, 'r', encoding='utf-8') as f:
            content = f.read()

        # Split into sections
        sections = self._split_sections(content)

        # Parse each section
        if 'EVENTS' in sections:
            self.events = self._parse_events(sections['EVENTS'])

        if 'ACTORS' in sections:
            self.actors = self._parse_actors(sections['ACTORS'])

        if 'RELATIONS' in sections:
            self.relations = self._parse_relations(sections['RELATIONS'])
            self._categorize_relations()

        return self

    def _split_sections(self, content):
        """Split DRS content into sections (EVENTS, ACTORS, RELATIONS)."""
        sections = {}
        current_section = None
        current_content = []

        for line in content.split('\n'):
            if line.startswith('» '):
                # Save previous section
                if current_section:
                    sections[current_section] = '\n'.join(current_content)

                # Start new section
                current_section = line.replace('» ', '').strip()
                current_content = []
            else:
                current_content.append(line)

        # Save last section
        if current_section:
            sections[current_section] = '\n'.join(current_content)

        return sections

    def _parse_events(self, events_section):
        """
        Parse EVENTS section.
        """
        events = []
        lines = events_section.split('\n')

        i = 0
        position = 0  # NEW: track document position
        while i < len(lines):
            line = lines[i].strip()

            # Look for event header: # T40 (follows) -> a
            if line.startswith('#') and '->' in line:
                event = self._parse_event_entry(line, lines[i:i + 3])
                if event:
                    event['position'] = position  # NEW: add position
                    events.append(event)
                    position += 1  # NEW: increment
                i += 3  # Skip FOL and DRS lines
            else:
                i += 1

        # Collect all temporal relations from events
        for event in events:
            if 'temporal_relations' in event:
                self.temporal_relations.extend(event['temporal_relations'])

        return events

    def _parse_event_entry(self, header_line, context_lines):
        """
        Parse a single event entry.

        Args:
            header_line: # T40 (follows) -> a
            context_lines: Following lines with FOL and DRS
        """
        # Parse header: # T40 (follows) -> a
        header_match = re.match(r'#\s+(T\d+)\s+\((.+?)\)\s+->\s+(\w+)', header_line)
        if not header_match:
            return None

        event_id, event_text, variable = header_match.groups()

        # Extract attributes from FOL/DRS line
        attributes = {}
        temp_relations = []

        for line in context_lines:
            if 'FOL:' in line or 'DRS:' in line:
                # Extract attributes like Type(a,State), Tense(a,Past), etc.
                attributes.update(self._extract_attributes(line))

                # Extract temporal relations embedded in this event
                temp_relations.extend(self._extract_temporal_relations_from_event(line, variable))

        event = {
            'id': event_id,
            'text': event_text,
            'variable': variable,
            'type': attributes.get('Type'),
            'tense': attributes.get('Tense'),
            'aspect': attributes.get('Aspect'),
            'vform': attributes.get('Vform'),
            'pos': attributes.get('Pos'),
            'attributes': attributes,
            'temporal_relations': temp_relations  # NEW: store relations
        }

        return event

    def _extract_attributes(self, line):
        """
        Extract attributes from FOL/DRS line.

        Examples:
        - Type(a,State) → {'Type': 'State'}
        - Tense(a,Past) → {'Tense': 'Past'}
        - occursBefore(a,b) → temporal relation (extracted separately)
        """
        attributes = {}

        # Pattern for attribute(variable, value)
        attr_pattern = r'(\w+)\([a-z]+,\s*([^)]+)\)'
        matches = re.findall(attr_pattern, line)

        for attr_name, attr_value in matches:
            # Skip relation-like attributes (will be handled separately)
            if attr_name in ['relationRole', 'occursBefore', 'occursAfter',
                             'overlaps', 'during', 'resultState', 'at_time']:
                continue

            attributes[attr_name] = attr_value.strip()

        return attributes

    def _extract_temporal_relations_from_event(self, line, event_variable):
        """
        Extract temporal relations embedded in event properties.

        Args:
            line: FOL/DRS line containing relations
            event_variable: Variable of current event (e.g., 'a', 'b')

        Returns:
            list: Temporal relations where this event is the source
        """
        relations = []

        # Pattern: occursBefore(a,b) means a occurs before b
        occurs_before = re.findall(rf'occursBefore\({event_variable},(\w+)\)', line)
        for target in occurs_before:
            relations.append({
                'source': event_variable,
                'type': 'occursBefore',
                'target': target
            })

        # Pattern: occursAfter(a,b) means a occurs after b
        occurs_after = re.findall(rf'occursAfter\({event_variable},(\w+)\)', line)
        for target in occurs_after:
            relations.append({
                'source': event_variable,
                'type': 'occursAfter',
                'target': target
            })

        # Pattern: overlaps(a,b) means a overlaps with b
        overlaps = re.findall(rf'overlaps\({event_variable},(\w+)\)', line)
        for target in overlaps:
            relations.append({
                'source': event_variable,
                'type': 'overlaps',
                'target': target
            })

        return relations

    def _parse_actors(self, actors_section):
        """
        Parse ACTORS section.

        Example:
        # T1 -> The book
        # T2 -> an international organization
        """
        actors = {}

        for line in actors_section.split('\n'):
            line = line.strip()
            if line.startswith('#'):
                # Parse: # T1 -> The book
                match = re.match(r'#\s+(T\d+)\s+->\s+(.+)', line)
                if match:
                    actor_id, actor_text = match.groups()
                    actors[actor_id] = actor_text.strip()

        return actors

    def _parse_relations(self, relations_section):
        """
        Parse RELATIONS section.

        Example:
        # T1 - agent - T40
        # T7 - objIdentity - T8
        """
        relations = []

        for line in relations_section.split('\n'):
            line = line.strip()
            if line.startswith('#'):
                # Parse: # T1 - agent - T40
                match = re.match(r'#\s+(T\d+)\s+-\s+(\w+)\s+-\s+(T\d+)', line)
                if match:
                    source, rel_type, target = match.groups()
                    relations.append({
                        'source': source,
                        'type': rel_type,
                        'target': target
                    })

        return relations

    def _categorize_relations(self):
        """Separate relations into temporal and semantic."""
        temporal_types = {
            'occursBefore', 'occursAfter', 'overlaps', 'during',
            'resultState', 'at_time', 'completedBefore', 'TLINK'
        }

        for rel in self.relations:
            if any(t in rel['type'] for t in temporal_types):
                self.temporal_relations.append(rel)
            else:
                self.semantic_relations.append(rel)

    def _get_temporally_ordered_events(self):
        """
        Order events using extracted temporal relations (occursBefore, occursAfter).

        Returns:
            list: Events sorted by temporal order, or None if cannot determine
        """
        if not self.temporal_relations or len(self.temporal_relations) == 0:
            return None

        # Build temporal graph
        G = nx.DiGraph()

        # Add all events as nodes
        for event in self.events:
            G.add_node(event['variable'])

        # Add temporal edges (source BEFORE target)
        for rel in self.temporal_relations:
            rel_type = rel['type']
            source = rel['source']
            target = rel['target']

            if rel_type == 'occursBefore':
                G.add_edge(source, target)  # source happens before target
            elif rel_type == 'occursAfter':
                G.add_edge(target, source)  # target happens before source
            # Skip 'overlaps' - not an ordering relation

        # Try topological sort to get temporal order
        try:
            ordered_vars = list(nx.topological_sort(G))

            # Map variables back to event objects
            var_to_event = {e['variable']: e for e in self.events}
            ordered_events = [var_to_event[v] for v in ordered_vars if v in var_to_event]
            #print(f"Temporal relations found: {len(self.temporal_relations)}")
            ordered_events = list(nx.topological_sort(G))
            #print(f"Ordered {len(ordered_events)}/{len(self.events)} events")

            return ordered_events
        except nx.NetworkXError:
            # Cycle detected or disconnected graph - cannot determine full order
            return None

    # ========== Feature Extraction Methods ==========

    def get_event_count(self):
        """Total number of events."""
        return len(self.events)

    def get_event_type_distribution(self):
        """
        Distribution of event types.

        Returns:
            dict: {'State': 10, 'Process': 5, 'Transition': 8, None: 2}
        """
        return Counter(e['type'] for e in self.events)

    def get_tense_distribution(self):
        """Distribution of tenses."""
        return Counter(e['tense'] for e in self.events)

    def get_aspect_distribution(self):
        """Distribution of aspects."""
        return Counter(e['aspect'] for e in self.events)

    def get_temporal_relation_types(self):
        """
        Count of each temporal relation type.

        Returns:
            dict: {'occursBefore': 5, 'overlaps': 2, etc.}
        """
        return Counter(r['type'] for r in self.temporal_relations)

    def get_semantic_relation_types(self):
        """Count of each semantic relation type."""
        return Counter(r['type'] for r in self.semantic_relations)

    def get_actor_count(self):
        """Number of actors/participants."""
        return len(self.actors)

    def get_relation_count(self):
        """Total number of relations."""
        return len(self.relations)

    def get_temporal_density(self):
        """
        Temporal relation density: ratio of temporal relations to events.

        Higher density = more temporally structured narrative.
        """
        if self.get_event_count() == 0:
            return 0.0
        return len(self.temporal_relations) / self.get_event_count()

    def get_feature_vector(self):
        """
        Extract complete feature vector from DRS.

        Returns:
            dict: All extracted features
        """
        event_types = self.get_event_type_distribution()
        tenses = self.get_tense_distribution()
        aspects = self.get_aspect_distribution()
        temp_rels = self.get_temporal_relation_types()
        sem_rels = self.get_semantic_relation_types()

        return {
            # Basic counts
            'event_count': self.get_event_count(),
            'actor_count': self.get_actor_count(),
            'relation_count': self.get_relation_count(),
            'temporal_relation_count': len(self.temporal_relations),
            'semantic_relation_count': len(self.semantic_relations),

            # Event type distribution
            'state_count': event_types.get('State', 0),
            'process_count': event_types.get('Process', 0),
            'transition_count': event_types.get('Transition', 0),
            'state_ratio': event_types.get('State', 0) / max(self.get_event_count(), 1),
            'process_ratio': event_types.get('Process', 0) / max(self.get_event_count(), 1),
            'transition_ratio': event_types.get('Transition', 0) / max(self.get_event_count(), 1),

            # Tense distribution
            'past_count': tenses.get('Past', 0),
            'present_count': tenses.get('Present', 0),
            'future_count': tenses.get('Future', 0),

            # Aspect distribution
            'perfective_count': aspects.get('Perfective', 0),
            'progressive_count': aspects.get('Progressive', 0),

            # Temporal relations
            'occurs_before_count': temp_rels.get('occursBefore', 0),
            'occurs_after_count': temp_rels.get('occursAfter', 0),
            'overlaps_count': temp_rels.get('overlaps', 0),
            'during_count': temp_rels.get('during', 0),
            'result_state_count': temp_rels.get('resultState', 0),

            # Density metrics
            'temporal_density': self.get_temporal_density(),
            'relation_density': self.get_relation_count() / max(self.get_event_count(), 1),

            # Semantic relations
            'agent_count': sem_rels.get('agent', 0),
            'patient_count': sem_rels.get('patient', 0),
            'coreference_count': sem_rels.get('objIdentity', 0),

            'event_bigrams':self.get_event_bigrams(),
            'event_trigrams':self.get_event_trigrams(),

            # Raw data for semantic comparison
            'events': self.events,
            'temporal_relations_raw': self.temporal_relations
        }

    def get_event_bigrams(self):
        """Extract consecutive event bigrams using TEMPORAL order."""
        if len(self.events) < 2:
            return []

        # Get temporal ordering
        ordered_events = self._get_temporally_ordered_events()

        # Fallback to document order
        if ordered_events is None or len(ordered_events) == 0:
            ordered_events = sorted(self.events, key=lambda e: e.get('position', 0))

        # ADDED: Safety check
        if len(ordered_events) < 2:
            return []

        bigrams = []
        for i in range(len(ordered_events) - 1):
            event1 = ordered_events[i]
            event2 = ordered_events[i + 1]

            if isinstance(event1, dict) and isinstance(event2, dict):
                text1 = event1.get('text', '')
                text2 = event2.get('text', '')

                # ADDED: Skip if no text
                if not text1 or not text2:
                    continue

                verb1 = self._normalize_event(text1)
                verb2 = self._normalize_event(text2)
                bigrams.append((verb1, verb2))

        return bigrams

    def get_event_trigrams(self):
        """
        Extract consecutive event type triples (trigrams) using TEMPORAL order.

        Returns:
            list: List of (event_type1, event_type2, event_type3) tuples
        """
        if len(self.events) < 3:
            return []

        # Try to get temporal ordering from relations
        ordered_events = self._get_temporally_ordered_events()

        # Fallback to document order if temporal order unavailable
        if ordered_events is None or len(ordered_events) == 0:
            ordered_events = sorted(self.events, key=lambda e: e.get('position', 0))

        trigrams = []
        for i in range(len(ordered_events) - 2):
            event1 = ordered_events[i]
            event2 = ordered_events[i + 1]
            event3 = ordered_events[i + 2]

            # Robust extraction of event type
            if isinstance(event1, dict) and isinstance(event2, dict) and isinstance(event3, dict):
                text1 = event1.get('text','')
                text2 = event2.get('text','')
                text3 = event3.get('text','')
                if not text1 or not text2 or not text3:
                    continue
                verb1 = self._normalize_event(text1)
                verb2 = self._normalize_event(text2)
                verb3 = self._normalize_event(text3)
                trigrams.append((verb1, verb2, verb3))

        return trigrams

    def __repr__(self):
        return (f"DRSParser({self.get_event_count()} events, "
                f"{self.get_actor_count()} actors, "
                f"{self.get_relation_count()} relations)")


# ========== Convenience Functions ==========

def parse_drs_file(filepath):
    """
    Parse a DRS file and return parser object.

    Usage:
        parser = parse_drs_file('0_anchor_drs.txt')
        features = parser.get_feature_vector()
    """
    parser = DRSParser(filepath)
    parser.parse()
    return parser


def extract_features(filepath):
    """
    Quick function to extract features from a DRS file.

    Usage:
        features = extract_features('0_anchor_drs.txt')
    """
    parser = parse_drs_file(filepath)
    return parser.get_feature_vector()


# ========== Testing ==========

if __name__ == "__main__":
    import sys

    if len(sys.argv) < 2:
        print("Usage: python drs_parser.py <drs_file>")
        print("\nExample:")
        print("  python drs_parser.py 0_anchor_drs.txt")
        sys.exit(1)

    filepath = sys.argv[1]

    print(f"Parsing: {filepath}")
    print("=" * 60)

    parser = parse_drs_file(filepath)

    print(f"\n{parser}")
    print("\nEvent Type Distribution:", dict(parser.get_event_type_distribution()))
    print("Tense Distribution:", dict(parser.get_tense_distribution()))
    print("Temporal Relations:", dict(parser.get_temporal_relation_types()))
    print(f"\nTemporal Density: {parser.get_temporal_density():.3f}")

    print("\n" + "=" * 60)
    print("FEATURE VECTOR:")
    print("=" * 60)
    features = parser.get_feature_vector()
    for key, value in sorted(features.items()):
        print(f"  {key:30s}: {value}")
